name: verify-apprentice
description: Run Liatrio checker then enforce minified JSON
runs:
  using: composite
  steps:
    - uses: liatrio/github-actions/apprentice-action@master
    - shell: bash
      run: |
        BODY="$(curl -s http://localhost/)"
        node -e "const b=process.env.BODY; const m=JSON.stringify(JSON.parse(b)); if(b===m){process.exit(0)} else {console.error('not minified');process.exit(1)}"
