name: CI & CD

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t liatrio_exercise:latest .

      # start the container in the background and give it some time to fully start up
    - name: Run app to test
      run: |
        docker run -d -p 80:80 liatrio_exercise:latest
        sleep 7

    - name: Run tests
      uses: liatrio/github-actions/apprentice-action@v1.0.0

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        # To keep secret information hidden, use Github Secrets
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

      # github.run_number increments each run for versioning
    - name: Tag image for Docker Hub
      run: docker tag liatrio_exercise:latest docker.io/${{ secrets.DOCKER_USERNAME }}/liatrio_exercise:v${{ github.run_number }}

    - name: Push image to Docker Hub
      run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/liatrio_exercise:v${{ github.run_number }}

  
  deploy:
    needs: build 
    runs-on: ubuntu-latest
    steps:
      - name: SSH into AWS EC2 and deploy the versioned image
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          # pulls the exact image to run and replaces the running container automatically if turned EC2 is turned off and turned back on
          script: |
            docker pull docker.io/${{ secrets.DOCKER_USERNAME }}/liatrio_exercise:v${{ github.run_number }} 
            docker rm -f liatrio-app || true 
            docker run -d --name liatrio-app --restart unless-stopped -p 80:80 docker.io/${{ secrets.DOCKER_USERNAME }}/liatrio_exercise:v${{ github.run_number }}
