name: Workflow CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: run tests
    - uses: liatrio/github-actions/apprentice-action@master
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t liatrio_exercise:latest .


